[py-cpp] Force address to be unsigned:
This matches `array.array("L",...` and fixes a signedness mismatch on 32bit:
```
FAIL: Test passing of variants of void pointer arguments
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sftnight/build/AXEL/src/roottest/python/cpp/PyROOT_cpptests.py", line 62, in test12VoidPointerPassing
    self.assertEqual( addressofo.buffer_info()[0], Z.GimeAddressPtrPtr( addressofo ) )
AssertionError: 3079933240 != -1215034056
```

(cherry picked from commit 6704db21f01b60d0b512925f9457808c2b573eb8)