Avoid clash with std::identity from C++20:
```
In file included from input_line_24:1:
/private/tmp/workspace/src/roottest/root/meta/naming/execClassEditNormalize.C:37:60: error: reference to 'identity' is ambiguous
                               indexed_by< ordered_unique< identity< ComplexElement > >,
                                                           ^
/private/tmp/workspace/src/roottest/root/meta/naming/execClassEditNormalize.C:30:29: note: candidate found by name lookup is 'identity'
template <typename A> class identity { public: typedef A result_type; };
                            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__functional/identity.h:24:8: note: candidate found by name lookup is 'std::identity'
struct identity {
       ^
```