Remove stray int in python/stl/PyROOT_stltests.py
This should fix the test on fedora37 and fedora38, which complain
    TypeError: argument of type 'int' is not iterable
after the recent upgrade to Python 3.11.3.

(cherry picked from commit aac224d8c3c3878637dfb3740b72e5754ad7aa60)