Rename `regular` to avoid name clash with C++20 concepts class:
```
/private/tmp/workspace/src/roottest/root/meta/tclass/runpairs.C:72:4: error: reference to 'regular' is ambiguous
   regular r;
   ^
/private/tmp/workspace/src/roottest/root/meta/tclass/runpairs.C:50:7: note: candidate found by name lookup is 'regular'
class regular {
      ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/concepts:415:9: note: candidate found by name lookup is 'std::regular'
concept regular = semiregular<_Tp> && equality_comparable<_Tp>;
        ^
```