For multicore tests, the linking is dependent on the order of modules
842: Building CXX object root/multicore/CMakeFiles/poolManager.dir/testPoolManager.cpp.o
842: Linking CXX executable poolManager
842: /usr/bin/ld: CMakeFiles/poolManager.dir/testPoolManager.cpp.o: undefined reference to symbol '_ZN3tbb10interface78internal15task_arena_base19internal_initializeEv'
842: /usr/bin/ld: /home/oksana/CERN_sources/root/builds/lib/libtbb.so.2: error adding symbols: DSO missing from command line