Remove test for std::span:
We can rely on the stdlibs to provide a working version. Our backport
is frozen; we support what we support, which is less than what
is tested here, as can be seen by the failures appearing when
running this test with std::span instead of our backport.

I could maybe fix our backport but that seems not a good investment.

Diagnostics:
```
In file included from input_line_24:1:
/private/tmp/workspace/src/roottest/root/collection/arrayViewBasic.C:77:5: error: no matching function for call to 'show_int_array'
    show_int_array<std::span<const int>>({1, 2, 3, 4}); //Note initializer_list cannot contain non-const types, but span can.
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/tmp/workspace/src/roottest/root/collection/arrayViewBasic.C:59:6: note: candidate function template not viable: cannot convert initializer list argument to 'std::span<const int, 18446744073709551615ull>'
void show_int_array(T view)
     ^
/private/tmp/workspace/src/roottest/root/collection/arrayViewBasic.C:29:31: error: no member named 'at' in 'std::span<int, 18446744073709551615ull>'
            std::cout << view.at(i);
                         ~~~~ ^
/private/tmp/workspace/src/roottest/root/collection/arrayViewBasic.C:61:4: note: in instantiation of function template specialization 'show_int_array_at<std::span<int, 18446744073709551615ull> >' requested here
   show_int_array_at(view);
   ^
/private/tmp/workspace/src/roottest/root/collection/arrayViewBasic.C:74:5: note: in instantiation of function template specialization 'show_int_array<std::span<int, 18446744073709551615ull> >' requested here
    show_int_array<std::span<int>>(good_old_c_array);
    ^
/private/tmp/workspace/src/roottest/root/collection/arrayViewBasic.C:29:31: error: no member named 'at' in 'std::span<const int, 18446744073709551615ull>'
            std::cout << view.at(i);
                         ~~~~ ^
/private/tmp/workspace/src/roottest/root/collection/arrayViewBasic.C:61:4: note: in instantiation of function template specialization 'show_int_array_at<std::span<const int, 18446744073709551615ull> >' requested here
   show_int_array_at(view);
   ^
/private/tmp/workspace/src/roottest/root/collection/arrayViewBasic.C:76:5: note: in instantiation of function template specialization 'show_int_array<std::span<const int, 18446744073709551615ull> >' requested here
    show_int_array<std::span<const int>>(vector);
    ^
```

(cherry picked from commit 72411b4c42061a72b5a11adfb4b701c54244b39b)